feat: allow multiple operators
keep-starknet-strange/piltover pull request #16
Opened 2024-02-19 17:42 UTC by TAdev0

- [x] issue #9 
- [ ] follows contribution [guide](https://github.com/keep-starknet-strange/piltover/blob/main/Contributing.md)
- [ ] code change includes tests
- [ ] breaking change

This PR allows the Core contract to register multiple operators.

2024-02-19 17:45 UTC, TAdev0 commented
@glihm  hey :)

This is a first draft, and tests fail will fail as i didn't modify anything in Tests for now
I used a legacyMap as specified, but i think my implementation is not optimized.

Indeed, `get_operator` is more like a `is_operator` function, returning true if the address passed to the function is an operator. 
Maybe should we use some array to store all operators in the contract?

2024-02-19 19:04 UTC, glihm commented
> @glihm hey :)
> 
> This is a first draft! I used a legacyMap as specified, but i think my implementation is not optimized.
> 
> Indeed, `get_operator` is more like a `is_operator` function, returning true if the address passed to the function is an operator. Maybe should we use some array to store all operators in the contract?

Hey, thanks for the progress!
Hum, actually the very first objective of the hashmap is to check. So we're totally right and The solidity code is actually using `is_operator` so you can totally rename. :+1:
They are also using `register_operator` instead of `set_operator`. You can also rename it will be better.

Those names was because the first impl didn't add the support for multiple operators. :+1:

2024-02-19 19:05 UTC, glihm reviewed
Will wait the renaming for other review, good progress. :+1:

2024-02-19 19:05 UTC, glihm commented on src/config/component.cairo
> +        operator: LegacyMap<ContractAddress, bool>,
```suggestion
        operators: LegacyMap<ContractAddress, bool>,
```

2024-02-19 19:29 UTC, TAdev0 commented on src/config/component.cairo
> +        operator: LegacyMap<ContractAddress, bool>,
done

2024-02-19 19:31 UTC, TAdev0 commented
@glihm  PR updated :)

2024-02-22 03:17 UTC, glihm requested changes
Some minor comment on formatting, and we should be good to go!

2024-02-22 03:17 UTC, glihm commented on src/config/interface.cairo
> +    /// Gets an operator address.
```suggestion
    /// Verifies if the given address is an operator.
```

2024-02-22 03:17 UTC, glihm commented on src/config/interface.cairo
> +    /// True if the address is an operator.
```suggestion
    /// True if the address is an operator, false otherwise.
```

2024-02-22 03:17 UTC, glihm commented on src/config/interface.cairo
> +    fn is_operator(self: @T, address: ContractAddress) -> bool;
Missing documentation for the field `address`.
Should be like:
```
/// # Arguments
///
/// * `address` - <description here>
```

2024-02-22 03:17 UTC, glihm commented on src/config/tests/test_config.cairo
> +    assert(!mock.is_operator(c::OPERATOR()), 'expect 0 addr');
```suggestion
    assert(!mock.is_operator(c::OPERATOR()), '0 not operator');
```

2024-02-22 03:17 UTC, glihm commented on src/config/tests/test_config.cairo
> +    assert(!mock.is_operator(c::OTHER()), 'expect 0 addr');
'expect 0 addr' is not the correct message here.

2024-02-22 11:12 UTC, TAdev0 commented on src/config/interface.cairo
> +    /// Gets an operator address.
way better!

2024-02-22 11:16 UTC, TAdev0 commented on src/config/interface.cairo
> +    fn is_operator(self: @T, address: ContractAddress) -> bool;
true

2024-02-22 11:27 UTC, TAdev0 commented on src/config/tests/test_config.cairo
> +    assert(!mock.is_operator(c::OPERATOR()), 'expect 0 addr');
what do you think of 
```
    assert(!mock.is_operator(c::OPERATOR()), 'expect not operator');
```
?

2024-02-22 11:29 UTC, TAdev0 commented
@glihm  PR updated ! 
I changed the error message in tests for "expect not operator". Tell me if you prefer something else, like "operator already registered" ..

2024-02-26 18:25 UTC, b-j-roberts reviewed
I left a couple of things, thank you!

2024-02-26 18:25 UTC, b-j-roberts commented on src/config/component.cairo
> +            address == owner || self.operators.read(address)
calling `is_operator` here might make this more clear.

2024-02-26 18:25 UTC, b-j-roberts commented on src/config/interface.cairo
> +    fn register_operator(ref self: T, address: ContractAddress);
I think we should also add the `unregister_operator` function now as well.

2024-02-26 18:41 UTC, TAdev0 commented on src/config/component.cairo
> +            address == owner || self.operators.read(address)
done

2024-03-06 15:06 UTC, b-j-roberts approved these changes
Great work! Thank you.

2024-03-06 15:10 UTC, merged