feat : update updtae_state args
keep-starknet-strange/piltover pull request #17
Opened 2024-02-21 18:29 UTC by AkankshaAttavar

- [x] issue #
- [ ] follows contribution [guide](https://github.com/keep-starknet-strange/piltover/blob/main/Contributing.md)
- [x] code change includes tests
- [ ] breaking change

I have updated the requierd, Sorry Bymistakly closed the PR.

2024-02-22 03:24 UTC, glihm requested changes
Thanks for the keccak changes. :+1:
Some formatting and code organization and it looks great!

2024-02-22 03:24 UTC, glihm commented on package-lock.json
> +}
Why is this file for?

2024-02-22 03:24 UTC, glihm commented on src/appchain.cairo
> +
```suggestion
```
Those comment are not expected here. If some documentation have to be added, could you please add it in the interface definition instead of the implementation?

2024-02-22 03:24 UTC, glihm commented on src/onchain_data_fact_tree_encoder/onchain_data_fact_tree_encoder.cairo
> +mod OnchainDataFactTreeEncoder {
Please use `snake_case` for module names.

```suggestion
mod onchain_data_fact_tree_encoder {
```

2024-02-22 03:24 UTC, glihm commented on src/onchain_data_fact_tree_encoder/onchain_data_fact_tree_encoder.cairo
> +    struct data_availability_fact {
Please use `PascalCase` for structs.

```suggestion
    struct DataAvailabilityFact {
```

2024-02-22 03:24 UTC, glihm commented on src/onchain_data_fact_tree_encoder/onchain_data_fact_tree_encoder.cairo
> +    //The left child contains the data we care about and the right child contains on-chain data for the fact.
```suggestion
    // Encodes a GPS fact Merkle tree where the root has two children.
    // The left child contains the data we care about and the right child contains on-chain data for the fact.
```
Documentation of arguments is missing.
The expected form is:
```rust
/// # Arguments
///
/// * `program_output` - <description>
/// * `fact_data` - <description>

2024-02-22 03:24 UTC, glihm commented on src/onchain_data_fact_tree_encoder/onchain_data_fact_tree_encoder.cairo
> +        //Compute the hash of the fact Merkle tree.
```suggestion
        // Compute the hash of the fact Merkle tree.
```

2024-02-22 03:24 UTC, glihm commented on src/onchain_data_fact_tree_encoder/onchain_data_fact_tree_encoder.cairo
> +        //   We are only given its hash and length
```suggestion
        // The state transition fact is computed as a Merkle tree.
        // The root has two children.
        // The left child is a leaf that includes the main part - the information regarding
        // the state transition required by this contract.
        // The right child contains the onchain-data which shouldn't be accessed by this
        // We are only given its hash and length
```

2024-02-26 19:01 UTC, AkankshaAttavar commented on package-lock.json
> +}
Sorry, I have removed it.

2024-02-26 19:01 UTC, AkankshaAttavar commented on src/appchain.cairo
> +
Updated the comments

2024-02-26 19:02 UTC, AkankshaAttavar commented on src/onchain_data_fact_tree_encoder/onchain_data_fact_tree_encoder.cairo
> +    struct data_availability_fact {
Done

2024-02-26 19:02 UTC, AkankshaAttavar commented on src/onchain_data_fact_tree_encoder/onchain_data_fact_tree_encoder.cairo
> +    //The left child contains the data we care about and the right child contains on-chain data for the fact.
Done

2024-02-26 19:02 UTC, AkankshaAttavar commented on src/onchain_data_fact_tree_encoder/onchain_data_fact_tree_encoder.cairo
> +        //   We are only given its hash and length
Completed

2024-02-28 19:25 UTC, AkankshaAttavar commented
I have resolved the merge conflicts

2024-03-12 18:15 UTC, AkankshaAttavar commented on src/appchain.cairo
> +                onchain_data_hash: onchain_data_hash, onchain_data_size: onchain_data_size
resolved

2024-03-12 23:25 UTC, merged