feat: add upgradeability
keep-starknet-strange/piltover pull request #36
Opened 2024-07-19 12:43 UTC by byteZorvin

- issue #35 

This pr add upgradeability using the Openzeppelin's upgradeable component

2024-09-03 02:20 UTC, glihm requested changes

2024-09-03 02:20 UTC, glihm commented on src/appchain.cairo
> +            // This function can only be called by the owner
Comment that could be removed as code is self-explanatory.

2024-09-03 02:20 UTC, glihm commented on src/appchain.cairo
> +            // Replace the class hash upgrading the contract
Same here, comment could be removed as very self-explanatory.

2024-09-03 05:41 UTC, byteZorvin commented on src/appchain.cairo
> +            // This function can only be called by the owner
updated

2024-09-03 05:41 UTC, byteZorvin commented on src/appchain.cairo
> +            // Replace the class hash upgrading the contract
updated

2024-09-05 04:15 UTC, glihm approved these changes
We don't have a test for that, but could be handled in an other PR if you want.
Thanks for the contribution @byteZorvin! 🚀

2024-09-05 23:36 UTC, merged